### ISSUE TITLE
Doesn't render isomorphically

### ISSUE THREAD

**Issue by jamesjjk** [wangzuo/react-medium-editor#8]
Hi, nice wrapper but it doesn't render isomorphically :(

**Comment by wangzuo** [comment]
server sider rendering ?

**Comment by jamesjjk** [comment]
@wangzuo yes did you have server sider rendering working?

**Comment by pontusab** [comment]
@jamesjjk for now you can just move the dependency medium-editor to be importen within componentDidMount. In react-medium-editor/lib/editor.js

**Comment by wangzuo** [comment]
@pontusab is correct, the `medium-editor` package doesnt work in a node environment.

``` javascript
var ReactDOMServer = require('react-dom/server');
var Editor = require('react-medium-editor');

ReactDOMServer.renderToString(<Editor text="hello world"/>);
```

A solution may be removing the `medium-editor` dependency.

**Comment by oyeanuj** [comment]
@jamesjjk @wangzuo I apologize, I am not 100% clear on your recommendations above. Are you suggesting that we import or just render the `Editor` component in componentDidMount of our container component?

@wangzuo Any chance of making this compatible for node environments?

@jamesjjk What was the final solution you came up with here?

**Comment by oyeanuj** [comment]
@pontusab @wangzuo I apologize, I am not 100% clear on your recommendations above. Are you suggesting that we import or just render the `Editor` component in componentDidMount of our container component?

@wangzuo Any chance of making this compatible for node environments?

@jamesjjk What was the final solution you came up with here?

**Comment by jamesjjk** [comment]
Solution: https://github.com/jamesjjk/react-medium-editor

**Comment by rkoberg** [comment]
Can you make a pull request so it gets merged into the main project?

**Comment by oyeanuj** [comment]
@jamesjjk That wasn't working for me. This is what I am getting after making the change you suggested: 

```
[piping] error given was: ReferenceError: document is not defined
[1]     at Object.<anonymous> (/node_modules/medium-editor/dist/js/medium-editor.js:6:22)
```

That translates to the last line of this snippet: 

``` javascript
/*global self, document, DOMException */

/*! @source http://purl.eligrey.com/github/classList.js/blob/master/classList.js */

// Full polyfill for browsers with no classList support
if (!("classList" in document.createElement("_"))) {
```

Any ideas on what might be going wrong? @wangzuo @pontusab ?

**Comment by wangzuo** [comment]
The problem is `medium-editor` doesnt support server rendering (node environment).
`require('medium-editor')` in `componentDidMount` works for me. 
@oyeanuj how do you render the component on server side?
I just pushed a `server-fix` branch https://github.com/wangzuo/react-medium-editor/commit/9eac7db79fcb196e79670b25b256d2d3ef929982, you may try `babe-node example/server.js`.

**Comment by oyeanuj** [comment]
Hi @wangzuo, thanks for your fix! Here is why I was tripping up and I wonder if there is a better solution to my hack: 

In my component file, I was importing the editor:

``` javascript
import  Editor  from    'React-Medium-Editor';
//var Editor = require('react-medium-editor');
```

and thats where the error was being thrown even if I wasn't rendering on the server. Even if I tried assigning the require to a variable, still the same error was being thrown.

So I ended up doing the following: 
- Outside the component class: 

``` javascript
var Editor;
export default class MyEditor extends Component {
```
- In `componentDidMount`:

``` javascript
componentDidMount() {
    /* If I use the line below at the very top instead of the import, 
    I again get the `document` error, hence assigning to global variable here */
    Editor = require('react-medium-editor');
    this.setState({
        showEditor: true
    });
}
```
- In the `render` method:

``` javascript
render() {
    const renderEditor = () => {
        if (this.state.showEditor) {
            return <Editor />;
        }
    };

    return renderEditor();
}
```

While this works, it feels a little hacky. Is there anything else that I can do which is cleaner and allows me to just import the component and render it?

**Comment by oyeanuj** [comment]
Unfortunately, the above approach also breaks Hot Reloading with the following error messages:

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `MyEditor`.warning @ warning.js?8a56:45
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `MyEditor`.
```

Any pointers would be much helpful!

**Comment by wangzuo** [comment]
#13 

@oyeanuj the demo page http://wangzuo.github.io/react-medium-editor/ is updated with server side rendering. could you check the newest release (1.6.2)? I only tested it with webpack.
